name: Nix

on: []
  
jobs:
  develop:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: cachix/cachix-action@v12
      #   with:
      #     name: fcitx5-android
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Debug APK
        run: |
          nix develop .#noAS --command ./gradlew :app:assembleDebug
          nix develop .#noAS --command ./gradlew :assembleDebugPlugins
